Repository WildCodeSchool-2024-02/php-p2-strasgite, pull requests merged in 2024-04, with the labels that each got.

#2 Rajout du fichier db dist.php et ajout des variables globales.
  config/db dist.php
  database.sql
  public/assets/css/_footer.css
  public/assets/css/_globals.css
  public/assets/css/_header.css
  public/assets/css/_main.css
  public/assets/css/_rooms.css
  public/assets/css/style.css
  public/assets/images/facade.jpg
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/View/Home/bisous.html.twig
  src/View/Home/index.html.twig
  src/View/Home/test.html.twig
  src/View/Include/_footer.html.twig
  src/View/Include/_form.html.twig
  src/View/Include/_header.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEW REQUESTED

#4 Sprint 1 US_02 hotfix
  public/assets/css/_footer.css
Labels: REVIEW REQUESTED

#5 Sprint 01 us-03
  database.sql
  public/assets/css/room.css
  public/assets/css/style.css
  public/assets/images/room/room1-1.webp
  public/assets/images/room/room1-2.webp
  public/assets/images/room/room1-3.webp
  src/Controller/RoomController.php
  src/Model/RoomManager.php
  src/View/Room/room.html.twig
  src/View/Room/showRoom.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEW REQUESTED

#7 Création des pages connexion, inscription et intégration des chambres…
  EditDB.sql
  public/assets/css/_connect.css
  public/assets/css/_rooms.css
  public/assets/css/style.css
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/ConnectController.php
  src/Controller/RoomsController.php
  src/Model/ConnectManager.php
  src/Model/RoomsManager.php
  src/View/Account/userAccount.html.twig
  src/View/Connect/connect.html.twig
  src/View/Connect/inscription.html.twig
  src/View/Home/home.html.twig
  src/View/Include/_header.html.twig
  src/View/Item/add.html.twig
  src/View/Room/room.html.twig
  src/View/Room/rooms.html.twig
  src/View/Room/showRoom.html.twig
  src/routes.php
Labels: REVIEW REQUESTED

#8 Sprint_02 US_08
  database.sql
  public/assets/css/_dashboard.css
  public/assets/css/style.css
  public/assets/images/Dashboardbanner.jpg
  public/assets/images/roue-dentee (1).png
  src/Controller/DashboardController.php
  src/View/Dashboard/dashboard.html.twig
  src/routes.php
Labels: CONFLICTS RESOLVED

#9 Mise en page du module showRoom, partie présentation de la chambre
  database.sql
  public/assets/css/room.css
  public/assets/images/room/room1-3.webp
  src/View/Room/showRoom.html.twig
Labels: CONFLICTS RESOLVED

#11 Ajout de l'édition des chambres / Routing du Dashboard / Dashboard des utilisateurs
  EditDB.sql
  database.sql
  public/assets/css/_connect.css
  public/assets/css/_dashboard.css
  public/assets/css/_rooms.css
  public/assets/css/_temoignage.css
  public/assets/css/room.css
  src/Controller/DashboardController.php
  src/Controller/RoomsController.php
  src/Model/DashboardManager.php
  src/Model/RoomsManager.php
  src/View/Dashboard/dashboard.html.twig
  src/View/Dashboard/dashboardUsers.html.twig
  src/View/Include/_form.html.twig
  src/View/Include/_header.html.twig
  src/View/Room/roomEdit.html.twig
  src/View/Room/rooms.html.twig
  src/View/Room/showRoom.html.twig
  src/routes.php
Labels: REVIEW REQUESTED

#12 Création page contact avec formulaire et infos de contact
  public/assets/css/_contact.css
  public/assets/css/style.css
  src/Controller/ContactController.php
  src/Model/ContactManager.php
  src/View/Contact/contact.html.twig
  src/View/Include/_header.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEW REQUESTED

#13 Edition fichier database
  EditDB.sql
  database.sql
  src/View/Room/showRoom.html.twig
Labels: REVIEW REQUESTED

#14 Us 11 contact
  EditDB.sql
  database.sql
  public/assets/css/_dashboard.css
  public/assets/css/_footer.css
  public/assets/css/_temoignage.css
  public/assets/css/room.css
  src/Controller/ContactController.php
  src/View/Contact/result.html.twig
  src/View/Include/_footer.html.twig
  src/View/Include/_header.html.twig
  src/routes.php
Labels: REVIEW REQUESTED

#17 US.17 Ajout de la feature "Réservation de chambres"
  database.sql
  public/assets/css/_rooms.css
  public/assets/css/room.css
  public/assets/images/room1/room1-1.webp
  public/assets/images/room1/room1-2.webp
  public/assets/images/room1/room1-3.webp
  src/Controller/ReservationController.php
  src/Controller/RoomController.php
  src/Model/ReservationManager.php
  src/View/Room/showRoom.html.twig
  src/routes.php
Labels: REVIEW REQUESTED

#18 Sprint_03 US_19
  database.sql
  phpmd.xml
  public/assets/css/_dashboard.css
  public/assets/css/_header.css
  src/Controller/ConnectController.php
  src/Controller/DashboardController.php
  src/Model/DashboardManager.php
  src/View/Connect/dashboardusercreation.html.twig
  src/View/Dashboard/dashboard.html.twig
  src/View/Dashboard/dashboardUsers.html.twig
  src/View/Include/_header.html.twig
  src/View/Room/showRoom.html.twig
  src/routes.php
Labels: CONFLICTS RESOLVED, REVIEW REQUESTED

#21 SPRINT_03 hotfix_accueil
  public/assets/css/_homeblock.css
  public/assets/images/Strasview.png
  public/assets/images/strasgiteview.png
  src/View/Home/home.html.twig
Labels: REVIEW REQUESTED

#19 US.21 Crud user profile
  public/assets/css/_connect.css
  public/assets/css/room.css
  src/Controller/ConnectController.php
  src/Controller/DashboardController.php
  src/Controller/RoomController.php
  src/Model/ConnectManager.php
  src/View/Account/userAccount.html.twig
  src/View/Account/userAccountEdit.html.twig
  src/View/Include/_formUser.html.twig
  src/View/Room/rooms.html.twig
  src/routes.php
Labels: CONFLICTS, REVIEW REQUESTED

#20 Création page admin chambre + page add chambre
  database.sql
  public/assets/css/room.css
  public/assets/images/favicon.png
  public/assets/images/roue-dentee.png
  src/Controller/DashboardController.php
  src/Model/DashboardManager.php
  src/View/Dashboard/dashboard.html.twig
  src/View/Dashboard/dashboardRooms.html.twig
  src/View/Dashboard/dashboardUsers.html.twig
  src/View/Include/_header.html.twig
  src/View/Room/addRoom.html.twig
  src/View/Room/roomEdit.html.twig
  src/View/Room/showRoom.html.twig
  src/routes.php
Labels: CONFLICTS RESOLVED, REVIEW REQUESTED

#22 Affichage des réservations sur le profil des utilisateurs
  public/assets/css/_connect.css
  src/Controller/ConnectController.php
  src/Model/ReservationManager.php
  src/View/Account/userAccount.html.twig
Labels: REVIEW REQUESTED

#26 Dashboard des réservation (CRUD)
  public/assets/css/_connect.css
  public/assets/css/_dashboard.css
  public/assets/css/_dashboardEdit.css
  src/Controller/ConnectController.php
  src/Controller/DashboardController.php
  src/Model/AbstractManager.php
  src/Model/ReservationManager.php
  src/View/Account/userAccount.html.twig
  src/View/Dashboard/dashboardBooking.html.twig
  src/View/Dashboard/dashboardBookingEdit.html.twig
  src/routes.php
Labels: REVIEW REQUESTED

#27 Corrections en fonction de la BDD table reservation + diverses correc…
  database.sql
  public/assets/css/_dashboard.css
  src/Controller/DashboardController.php
  src/Model/DashboardManager.php
  src/Model/ReservationManager.php
  src/View/Dashboard/dashboardRooms.html.twig
  src/View/Dashboard/dashboardUsers.html.twig
  src/View/Room/addRoom.html.twig
  src/View/Room/showRoom.html.twig
Labels: REVIEW REQUESTED

#31 SPRINT_03 US_21 Dashboard Service
  database.sql
  phpmd.xml
  public/assets/css/_dashboard.css
  public/assets/css/_dashboardservice.css
  public/assets/css/_dashboarduser.css
  public/assets/css/room.css
  public/assets/css/style.css
  src/Controller/DashboardController.php
  src/Controller/ReservationController.php
  src/Controller/RoomController.php
  src/Model/DashboardManager.php
  src/Model/ReservationManager.php
  src/View/Dashboard/dashboard.html.twig
  src/View/Dashboard/dashboardRooms.html.twig
  src/View/Dashboard/dashboardService.html.twig
  src/View/Dashboard/dashboardUsers.html.twig
  src/routes.php
Labels: REVIEW REQUESTED

#32 Contenu des chambres 1
  database.sql
  public/assets/css/_dashboard.css
  public/assets/css/_dashboardEdit.css
  public/assets/css/_rooms.css
  public/assets/css/room.css
  src/Controller/RoomController.php
  src/Model/RoomManager.php
  src/View/Dashboard/dashboardBookingEdit.html.twig
  src/View/Include/_formRoom.html.twig
  src/View/Room/roomEdit.html.twig
  src/View/Room/rooms.html.twig
  src/routes.php
Labels: CONFLICTS, REVIEW REQUESTED

#33 Us.20 gestion messages admin
  public/assets/css/_contact.css
  public/assets/css/_dashboardMessages.css
  public/assets/css/style.css
  src/Controller/ContactController.php
  src/Controller/MessageController.php
  src/Model/ContactManager.php
  src/Model/MessageManager.php
  src/View/Contact/contact.html.twig
  src/View/Contact/result.html.twig
  src/View/Dashboard/dashboard.html.twig
  src/View/Dashboard/dashboardMessages.html.twig
  src/View/Dashboard/dashboardShowMessage.html.twig
  src/routes.php
Labels: REVIEW REQUESTED

#34 Header responsive en-dessous de 1000px avec menu burger
  database.sql
  public/assets/css/_header.css
  public/assets/css/_room.css
  public/assets/css/style.css
  src/View/Include/_header.html.twig
Labels: REVIEW REQUESTED

#37 Css chambres + feature de gestion des avis utilisateurs
  database.sql
  public/assets/css/_dashboard.css
  public/assets/css/_room.css
  public/assets/css/_rooms.css
  public/assets/css/style.css
  public/assets/images/room2/room2-1.webp
  public/assets/images/room3/room3-1.webp
  public/assets/images/room4/room4-1.webp
  src/Controller/DashboardAvisController.php
  src/Model/AbstractManager.php
  src/Model/AvisManager.php
  src/View/Dashboard/Avis/addAvis.html.twig
  src/View/Dashboard/Avis/index.html.twig
  src/View/Dashboard/Avis/show.html.twig
  src/View/Dashboard/dashboardBooking.html.twig
  src/View/Dashboard/dashboardRooms.html.twig
  src/View/Dashboard/dashboardService.html.twig
  src/View/Dashboard/dashboardUsers.html.twig
  src/View/Room/rooms.html.twig
  src/View/Room/showRoom.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: REVIEW REQUESTED

#38 Css chambres et responsive de la présentation
  database.sql
  public/assets/css/_dashboard.css
  public/assets/css/_room.css
  public/assets/css/_rooms.css
  public/assets/images/room2/room2-1.webp
  public/assets/images/room2/room2-2.webp
  public/assets/images/room2/room2-3.webp
  public/assets/images/room3/room3-1.webp
  public/assets/images/room3/room3-2.webp
  public/assets/images/room3/room3-3.webp
  public/assets/images/room4/room4-2.webp
  public/assets/images/room4/room4-3.webp
  src/View/Dashboard/Avis/show.html.twig
  src/View/Room/rooms.html.twig
  src/View/Room/showRoom.html.twig
Labels: REVIEW REQUESTED

#41 Build final présentation démo projet 2
  public/assets/css/_rooms.css
  public/assets/css/room.css
  public/assets/images/room4/room4-3.webp
  src/View/Account/userAccount.html.twig
  src/View/Connect/connect.html.twig
  src/View/Dashboard/Avis/show.html.twig
  src/View/Room/rooms.html.twig
Labels: REVIEW REQUESTED
